#!/bin/bash

XDG_DATA_HOME=$HOME/.local/share

mkdir /tmp/dotfiles
mkdir -p ~/.local/bin

# === zsh ===
# TODO: check if zsh is installed

ln .zshrc ~/.zshrc

# install zsh plugin
ZSH_PLUGINS_DIR=${XDG_DATA_HOME}/zsh/plugins/

git clone https://github.com/Aloxaf/fzf-tab ${ZSH_PLUGINS_DIR}/fzf-tab
git clone https://github.com/zdharma-continuum/fast-syntax-highlighting ${ZSH_PLUGINS_DIR}/fast-syntax-highlighting

# set zsh as default (for 42)
# ipa user-mod $USER --shell /bin/zsh

# === nvim ===
# TODO: check if nvim is installed

ln -s ./.config/nvim ~/.config/nvim

# === posh ===
# TODO: if posh is already install continue
curl -s https://ohmyposh.dev/install.sh | bash -s -- -d ~/.local/bin
mv ~/.local/bin/oh-my-posh ~/.local/bin/posh
mkdir -p .config/posh
ln .config/posh/my.json ~/.config/posh/my.json

# === fzf ===
# TODO: if fzf is already install continue
curl -L https://github.com/junegunn/fzf/releases/download/v0.74.0/fzf-0.74.0-linux_amd64.tar.gz -o /tmp/dotfiles/fzf.tar.gz
tar -C ~/.local/bin -xf /tmp/dotfiles/fzf.tar.gz

# man: /usr/share/man/man1/fzf.1.gz
# autocomplition: 

# === bat ===
# TODO: if bat is already install continue
curl -L https://github.com/sharkdp/bat/releases/download/v0.26.1/bat-v0.26.1-x86_64-unknown-linux-gnu.tar.gz -o /tmp/dotfiles/bat.tar.gz
tar -C ~/.local/bin -xf /tmp/dotfiles/bat.tar.gz bat-v0.26.1-x86_64-unknown-linux-gnu/bat --strip-components=1
mkdir -p .config/bat/
ln .config/bat/config ~/.config/bat/config

# man: /usr/share/man/man1/bat.1.gz
# autocomplition zsh: /usr/share/zsh/site-functions/_bat
# autocomplition bash: /usr/share/bash-completion/completions/bat

# == post instalation ==
rm -rf /tmp/dotfiles

